import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { verifyToken } from '@/lib/auth';

// -------------------------------------------------------------
// HELPER: WhatsApp Auto-Poster
// -------------------------------------------------------------
async function postToWhatsApp(token: string, phoneId: string, groupId: string, text: string, imageUrl: string) {
  try {
    const res = await fetch(`https://graph.facebook.com/v19.0/${phoneId}/messages`, {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ messaging_product: 'whatsapp', to: groupId, type: 'image', image: { link: imageUrl, caption: text } })
    });
    return res.ok;
  } catch(e) { return false; }
}

// -------------------------------------------------------------
// HELPER: Instagram Auto-Poster
// -------------------------------------------------------------
async function postToInstagram(token: string, accountId: string, imageUrl: string, caption: string) {
  try {
    const containerRes = await fetch(`https://graph.facebook.com/v19.0/${accountId}/media?image_url=${encodeURIComponent(imageUrl)}&caption=${encodeURIComponent(caption)}&access_token=${token}`, { method: 'POST' });
    const containerData = await containerRes.json();
    if (containerData.id) {
      await fetch(`https://graph.facebook.com/v19.0/${accountId}/media_publish?creation_id=${containerData.id}&access_token=${token}`, { method: 'POST' });
      return true;
    }
    return false;
  } catch(e) { return false; }
}

// -------------------------------------------------------------
// HELPER: Twitter Auto-Poster (v2)
// -------------------------------------------------------------
async function postToTwitter(bearerToken: string, text: string) {
  try {
    const res = await fetch('https://api.twitter.com/2/tweets', {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${bearerToken}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ text })
    });
    return res.ok;
  } catch (e) { return false; }
}

// GET: List posts
export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const page = parseInt(searchParams.get('page') || '1');
    const limit = parseInt(searchParams.get('limit') || '10');
    const search = searchParams.get('search') || '';
    const tag = searchParams.get('tag') || '';
    const status = searchParams.get('status') || '';
    const publishedOnly = searchParams.get('published') === 'true';

    const where: any = {};
    if (search) {
      where.OR = [
        { title: { contains: search, mode: 'insensitive' } },
        { content: { contains: search, mode: 'insensitive' } }
      ];
    } else if (publishedOnly) {
      // Vacancy Expiry Logic: Hide expired posts in normal feed
      where.OR = [
        { expiryDate: null },
        { expiryDate: { gte: new Date() } }
      ];
    }
    
    if (status && status !== 'All') {
      where.status = status;
    }
    if (publishedOnly) {
      where.status = 'Published';
      where.publishedAt = { lte: new Date() };
    }
    if (tag) {
      where.tags = { some: { tag: { name: tag } } };
    }

    const [posts, total] = await Promise.all([
      prisma.blogPost.findMany({
        where,
        include: { author: { select: { name: true, email: true } }, tags: { include: { tag: true } } },
        orderBy: { createdAt: 'desc' },
        skip: (page - 1) * limit,
        take: limit,
      }),
      prisma.blogPost.count({ where }),
    ]);

    // Format tags array
    const formattedPosts = posts.map((p: any) => ({
      ...p,
      tags: p.tags.map((t: any) => t.tag.name)
    }));

    const response = NextResponse.json({
      posts: formattedPosts,
      total,
      page,
      totalPages: Math.ceil(total / limit)
    });
    
    // Cache for 60 seconds on CDN (Edge), stale-while-revalidate for 1 hour
    response.headers.set('Cache-Control', 'public, s-maxage=60, stale-while-revalidate=3600');
    return response;
  } catch (error) {
    console.error('Error fetching posts:', error);
    return NextResponse.json({ error: 'Failed to fetch posts' }, { status: 500 });
  }
}

// POST: Create post
export async function POST(request: NextRequest) {
  try {
    const authToken = request.cookies.get('automata_auth_token')?.value;
    const user = authToken ? verifyToken(authToken) : null;
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const body = await request.json();
    const { title, subtitle, slug, content, excerpt, featuredImage, status, seoTitle, seoDescription, seoKeywords, socialCaptions, socialHashtags, scheduledAt, autoGenerated, tags = [] } = body;

    if (!title || !content) {
      return NextResponse.json({ error: 'Title and content are required' }, { status: 400 });
    }

    let finalSlug = slug || title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, '');
    
    // Check if slug exists
    const existing = await prisma.blogPost.findUnique({ where: { slug: finalSlug } });
    if (existing) {
      finalSlug = `${finalSlug}-${Date.now()}`;
    }

    const postData: any = {
      title,
      subtitle,
      slug: finalSlug,
      content,
      excerpt,
      featuredImage,
      status: status || 'Draft',
      seoTitle,
      seoDescription,
      seoKeywords,
      socialCaptions,
      socialHashtags,
      autoGenerated: !!autoGenerated,
      authorId: user.userId
    };

    if (status === 'Published') {
      postData.publishedAt = new Date();
    } else if (status === 'Scheduled' && scheduledAt) {
      postData.scheduledAt = new Date(scheduledAt);
    }

    const newPost = await prisma.blogPost.create({ data: postData });

    // Handle tags
    if (Array.isArray(tags) && tags.length > 0) {
      for (const tagName of tags) {
        const tagSlug = tagName.toLowerCase().replace(/[^a-z0-9]+/g, '-');
        const tag = await prisma.tag.upsert({
          where: { slug: tagSlug },
          update: {},
          create: { name: tagName, slug: tagSlug }
        });
        await prisma.postTag.create({
          data: { postId: newPost.id, tagId: tag.id }
        });
      }
    }

    // Social Media Auto-Poster Logic
    if (status === 'Published') {
      try {
        const savedKeys = await prisma.autoBlogSettings.findUnique({ where: { id: 'default' } });
        if (savedKeys) {
          const socialCaption = socialCaptions || `Check out our latest article: ${title}\n\nRead more here: https://www.knowora.in/blog/${newPost.slug}\n\n${socialHashtags || ''}`;
          const socialImageUrl = `https://www.knowora.in/api/og?title=${encodeURIComponent(title)}&bg=${encodeURIComponent(featuredImage)}`;

          // 1. WhatsApp
          if (savedKeys.whatsappToken && savedKeys.whatsappPhoneId && savedKeys.whatsappGroupId) {
            await postToWhatsApp(savedKeys.whatsappToken, savedKeys.whatsappPhoneId, savedKeys.whatsappGroupId, socialCaption, socialImageUrl);
          }

          // 2. Instagram
          if (savedKeys.instagramToken && savedKeys.instagramAccountId) {
            await postToInstagram(savedKeys.instagramToken, savedKeys.instagramAccountId, socialImageUrl, socialCaption);
          }

          // 3. Twitter
          if (savedKeys.twitter) {
            await postToTwitter(savedKeys.twitter, socialCaption);
          }

          // 4. Telegram
          if (savedKeys.telegramToken && savedKeys.telegramChatId) {
            await fetch(`https://api.telegram.org/bot${savedKeys.telegramToken}/sendMessage`, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({
                chat_id: savedKeys.telegramChatId,
                text: socialCaption,
                parse_mode: 'HTML'
              })
            }).catch(() => {});
          }

          // 5. OneSignal Push Notifications
          if (savedKeys.onesignalAppId && savedKeys.onesignalApiKey) {
            await fetch('https://onesignal.com/api/v1/notifications', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'Authorization': `Basic ${savedKeys.onesignalApiKey}`
              },
              body: JSON.stringify({
                app_id: savedKeys.onesignalAppId,
                included_segments: ['Subscribed Users'],
                headings: { en: title },
                contents: { en: excerpt || 'Read our latest post!' },
                url: `https://www.knowora.in/blog/${newPost.slug}`,
                big_picture: socialImageUrl
              })
            }).catch(() => {});
          }
        }
      } catch (err) {
        console.error('Failed to trigger social media auto-post', err);
      }
    }

    return NextResponse.json({ success: true, post: newPost }, { status: 201 });
  } catch (error) {
    console.error('Error creating post:', error);
    return NextResponse.json({ error: 'Failed to create post' }, { status: 500 });
  }
}

// DELETE: Delete post
export async function DELETE(request: NextRequest) {
  try {
    const authToken = request.cookies.get('automata_auth_token')?.value;
    const user = authToken ? verifyToken(authToken) : null;
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');

    if (!id) return NextResponse.json({ error: 'ID required' }, { status: 400 });

    await prisma.blogPost.delete({ where: { id } });
    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error deleting post:', error);
    return NextResponse.json({ error: 'Failed to delete post' }, { status: 500 });
  }
}
