import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { revalidatePath } from 'next/cache';

export const dynamic = 'force-dynamic';

const SECRET_KEY = 'knowora-secret-2026';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { secret, title, content, excerpt, slug, gridBox, officialApplyUrl, jobStates, qualifications } = body;

    // Verify secret
    if (secret !== SECRET_KEY) {
      return NextResponse.json({ error: 'Unauthorized: Invalid secret key' }, { status: 401 });
    }

    if (!title || !content) {
      return NextResponse.json({ error: 'Title and content are required' }, { status: 400 });
    }

    let finalSlug = slug || title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
    if (!finalSlug) finalSlug = `blog-${Date.now()}`;

    const existing = await prisma.blogPost.findUnique({ where: { slug: finalSlug } });
    if (existing) {
      finalSlug = `${finalSlug}-${Date.now().toString().slice(-4)}`;
    }

    const imagePrompt = encodeURIComponent(`${title.slice(0, 50)} India modern official high resolution`);
    const featuredImage = `https://image.pollinations.ai/prompt/${imagePrompt}?width=1600&height=900&nologo=true`;

    const post = await prisma.blogPost.create({
      data: {
        title,
        slug: finalSlug,
        content,
        excerpt: excerpt || title,
        featuredImage,
        status: 'Published',
        publishedAt: new Date(),
        gridBox: gridBox || 'latestJobs',
        seoTitle: title,
        seoDescription: excerpt || title,
        seoKeywords: title,
        jobStates: jobStates || [],
        qualifications: qualifications || [],
        officialApplyUrl: officialApplyUrl || null,
        autoGenerated: false,
        allowAutoUpdate: false,
      }
    });

    try {
      revalidatePath('/', 'layout');
      revalidatePath('/blog', 'layout');
    } catch (e) {}

    return NextResponse.json({
      success: true,
      message: 'Blog published successfully from AI!',
      url: `https://knowora.in/blog/${post.slug}`,
      id: post.id
    });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
