import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

// Telegram Bot Webhook Handler
// Set webhook via: https://api.telegram.org/bot<TOKEN>/setWebhook?url=https://yourdomain.com/api/telegram/webhook
export async function POST(request: Request) {
  try {
    const body = await request.json();

    // Extract message from Telegram update
    const message = body?.message;
    if (!message || !message.text) {
      return NextResponse.json({ ok: true }); // Ignore non-text updates
    }

    const chatId = message.chat.id;
    const text = message.text.trim();
    const senderName = message.from?.first_name || 'Unknown';

    // Verify this is from an authorized admin (check against stored Telegram Chat ID)
    const siteSettings = await prisma.siteSettings.findUnique({ where: { id: 'default' } });
    let authorizedChatId = '';
    try {
      if (siteSettings?.aiApiKey?.startsWith('{')) {
        const parsed = JSON.parse(siteSettings.aiApiKey);
        authorizedChatId = parsed.telegramChatId || '';
      }
    } catch (e) {}

    // Allow if chat ID matches OR if no chat ID is configured (open mode)
    const isAuthorized = !authorizedChatId || String(chatId) === String(authorizedChatId);
    
    if (!isAuthorized) {
      // Send rejection message
      await sendTelegramMessage(chatId, '❌ You are not authorized to use this bot.');
      return NextResponse.json({ ok: true });
    }

    // Handle commands
    if (text.startsWith('/start')) {
      await sendTelegramMessage(chatId, 
        `🚀 *Anti Gravity Auto-Blog Bot*\n\n` +
        `Welcome ${senderName}! Here's what I can do:\n\n` +
        `📝 *Add Keyword:* Just type any topic/keyword and I'll add it to the auto-blog queue.\n\n` +
        `📊 */stats* - View blog statistics\n` +
        `📋 */queue* - View pending keywords\n` +
        `🗑️ */clear* - Clear all pending keywords\n\n` +
        `Try sending me a topic like: "SSC CGL 2025 Notification"`
      );
      return NextResponse.json({ ok: true });
    }

    if (text.startsWith('/stats')) {
      const [totalPosts, pendingKw, totalAuto] = await Promise.all([
        prisma.blogPost.count(),
        prisma.autoBlogKeyword.count({ where: { status: 'pending' } }),
        prisma.blogPost.count({ where: { autoGenerated: true } })
      ]);
      await sendTelegramMessage(chatId,
        `📊 *Blog Statistics*\n\n` +
        `📝 Total Posts: ${totalPosts}\n` +
        `✨ AI Generated: ${totalAuto}\n` +
        `⏳ Pending Keywords: ${pendingKw}`
      );
      return NextResponse.json({ ok: true });
    }

    if (text.startsWith('/queue')) {
      const pending = await prisma.autoBlogKeyword.findMany({
        where: { status: 'pending' },
        orderBy: [{ priority: 'desc' }, { createdAt: 'asc' }],
        take: 10
      });
      if (pending.length === 0) {
        await sendTelegramMessage(chatId, '📋 Queue is empty! Send me a topic to add.');
      } else {
        const list = pending.map((k, i) => `${i + 1}. ${k.keyword} (Priority: ${k.priority})`).join('\n');
        await sendTelegramMessage(chatId, `📋 *Pending Keywords (${pending.length}):*\n\n${list}`);
      }
      return NextResponse.json({ ok: true });
    }

    if (text.startsWith('/clear')) {
      const deleted = await prisma.autoBlogKeyword.deleteMany({ where: { status: 'pending' } });
      await sendTelegramMessage(chatId, `🗑️ Cleared ${deleted.count} pending keywords.`);
      return NextResponse.json({ ok: true });
    }

    // Default: Treat as keyword to add
    // Check for priority prefix like "!high SSC CGL" or "!urgent UPSC"
    let priority = 5;
    let keyword = text;
    if (text.startsWith('!urgent') || text.startsWith('!high')) {
      priority = 10;
      keyword = text.replace(/^!(urgent|high)\s*/i, '').trim();
    } else if (text.startsWith('!low')) {
      priority = 1;
      keyword = text.replace(/^!low\s*/i, '').trim();
    }

    if (!keyword || keyword.length < 3) {
      await sendTelegramMessage(chatId, '⚠️ Keyword too short. Send at least 3 characters.');
      return NextResponse.json({ ok: true });
    }

    // Check for duplicate
    const existing = await prisma.autoBlogKeyword.findFirst({
      where: { keyword: { equals: keyword, mode: 'insensitive' }, status: 'pending' }
    });
    if (existing) {
      await sendTelegramMessage(chatId, `⚠️ "${keyword}" is already in the queue.`);
      return NextResponse.json({ ok: true });
    }

    // Add to queue
    await prisma.autoBlogKeyword.create({
      data: { keyword, priority, status: 'pending' }
    });

    const pendingCount = await prisma.autoBlogKeyword.count({ where: { status: 'pending' } });
    await sendTelegramMessage(chatId,
      `✅ *Keyword Added!*\n\n` +
      `📌 Topic: ${keyword}\n` +
      `⚡ Priority: ${priority}/10\n` +
      `📋 Queue Position: ${pendingCount}\n\n` +
      `The AI will automatically write a blog post on this topic in the next cycle! 🚀`
    );

    return NextResponse.json({ ok: true });
  } catch (error: any) {
    console.error('[Telegram Webhook] Error:', error);
    return NextResponse.json({ ok: true }); // Always return 200 to Telegram
  }
}

// Helper function to send Telegram messages
async function sendTelegramMessage(chatId: number | string, text: string) {
  try {
    const siteSettings = await prisma.siteSettings.findUnique({ where: { id: 'default' } });
    let botToken = '';
    if (siteSettings?.aiApiKey?.startsWith('{')) {
      const parsed = JSON.parse(siteSettings.aiApiKey);
      botToken = parsed.telegramToken || '';
    }
    if (!botToken) {
      console.error('[Telegram] No bot token configured');
      return;
    }
    await fetch(`https://api.telegram.org/bot${botToken}/sendMessage`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        chat_id: chatId,
        text,
        parse_mode: 'Markdown'
      })
    });
  } catch (err) {
    console.error('[Telegram] Send message failed:', err);
  }
}

// GET endpoint for health check and setup instructions
export async function GET() {
  return NextResponse.json({
    status: 'active',
    instructions: 'Set Telegram webhook to: https://yourdomain.com/api/telegram/webhook',
    commands: ['/start', '/stats', '/queue', '/clear'],
    note: 'Send any text to add it as a keyword to the auto-blog queue.'
  });
}
