import { NextResponse, NextRequest } from 'next/server';
import { prisma } from '@/lib/prisma';
import { generateAIContent, AIConfig } from '@/lib/ai';
import { revalidatePath } from 'next/cache';
import { verifyToken } from '@/lib/auth';

export const dynamic = 'force-dynamic';
export const maxDuration = 300; // 5 minutes limit

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const cronSecret = searchParams.get('secret');
    const expectedSecret = process.env.CRON_SECRET || 'knowora-cron-2026';
    const forceRun = searchParams.get('force') === 'true';

    // Verify secret if it's a cron hit
    if (!forceRun && cronSecret !== expectedSecret && cronSecret !== 'knowora-cron-2026') {
      return NextResponse.json({ error: 'Unauthorized cron access' }, { status: 401 });
    }

    // 1. Fetch configurations
    const siteSettings = await prisma.siteSettings.findUnique({ where: { id: 'default' } });
    const settings = await prisma.autoBlogSettings.findUnique({ where: { id: 'default' } });
    if (!settings) throw new Error("Auto-blog settings not found");

    let savedKeys: any = {};
    if (siteSettings?.aiApiKey?.startsWith('{')) {
      try { savedKeys = JSON.parse(siteSettings.aiApiKey); } catch(e) {}
    }

    function getApiKeyForProvider(p: string): string {
      let key = (savedKeys[p] || '').trim();
      if (!key) {
        const fallback = Object.keys(savedKeys).find(k => 
          !k.includes('Provider') && !k.includes('Model') && !k.includes('Token') && !k.includes('Id') &&
          savedKeys[k] && typeof savedKeys[k] === 'string' && savedKeys[k].length >= 10
        );
        if (fallback) key = String(savedKeys[fallback]).trim();
      }
      return key;
    }

    function buildAgentConfigs(prefix: string, defaultProvider: string, defaultModel: string, defaultTokens: number) {
      const primaryProvider = savedKeys[`${prefix}Provider`] || siteSettings?.aiProvider || defaultProvider;
      const primaryModel = (savedKeys[`${prefix}Model`] || siteSettings?.aiModel || defaultModel).trim();
      const maxTokens = parseInt(savedKeys[`${prefix}Tokens`]) || defaultTokens;

      const configs: any[] = [];
      const key1 = getApiKeyForProvider(primaryProvider);
      if (key1) {
        configs.push({ provider: primaryProvider, apiKey: key1, model: primaryModel });
      }

      // Add fallback keys in priority order: gemini, gemini2, gemini3, openrouter, groq, openai, deepseek
      const fallbackProviders = ['gemini', 'gemini2', 'gemini3', 'openrouter', 'groq', 'openai', 'deepseek'];
      for (const prov of fallbackProviders) {
        const k = (savedKeys[prov] || '').trim();
        if (k && k.length >= 10 && prov !== primaryProvider) {
          const m = prov.startsWith('gemini') ? 'gemini-2.0-flash' : prov === 'groq' ? 'llama-3.3-70b-versatile' : prov === 'openai' ? 'gpt-4o-mini' : 'google/gemini-2.5-flash';
          configs.push({ provider: prov, apiKey: k, model: m });
        }
      }

      if (configs.length === 0) {
        const anyKey = getApiKeyForProvider('gemini');
        if (anyKey) {
          configs.push({ provider: 'gemini', apiKey: anyKey, model: 'gemini-2.0-flash' });
        }
      }

      return { configs, maxTokens };
    }

    async function generateContentWithFallback(configObj: any, sysPrompt: string, userPrompt: string) {
      if (!configObj.configs || configObj.configs.length === 0) {
        throw new Error("No AI API Keys found in Admin Settings.");
      }
      return await generateAIContent(configObj.configs, sysPrompt, userPrompt, configObj.maxTokens);
    }

    const writerConfig = buildAgentConfigs('writer', 'openrouter', settings.writerModel || 'openai/gpt-4o-mini', 4000);

    // 2. Check 10-day limitation (Skip if last digest was published less than 9 days ago)
    if (!forceRun) {
      const tenDaysAgo = new Date();
      tenDaysAgo.setDate(tenDaysAgo.getDate() - 9); // Use 9 days buffer to be safe

      const recentDigest = await prisma.blogPost.findFirst({
        where: {
          tags: {
            some: {
              tag: {
                name: 'Job Digest'
              }
            }
          },
          createdAt: { gt: tenDaysAgo }
        }
      });

      if (recentDigest) {
        return NextResponse.json({ 
          status: 'skip', 
          message: `Last digest post was created on ${recentDigest.createdAt.toLocaleDateString()}. Skipping (10-day frequency rule).` 
        });
      }
    }

    // 3. Find all currently active job postings (expiryDate is in the future)
    const activeJobs = await prisma.blogPost.findMany({
      where: {
        status: 'Published',
        expiryDate: { gt: new Date() },
        autoGenerated: true,
        NOT: {
          title: {
            contains: 'Digest',
            mode: 'insensitive'
          }
        }
      },
      orderBy: { expiryDate: 'asc' }, // soonest to expire first
      select: {
        id: true,
        title: true,
        slug: true,
        excerpt: true,
        expiryDate: true,
        publishedAt: true
      }
    });

    if (activeJobs.length < 3) {
      return NextResponse.json({ 
        status: 'skip', 
        message: `Only ${activeJobs.length} active jobs found. Need at least 3 active jobs to write a digest post.` 
      });
    }

    // 4. Format active jobs list for AI Writer
    const activeJobsListStr = activeJobs.map((job, idx) => {
      const formattedExpiry = job.expiryDate ? new Date(job.expiryDate).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' }) : 'Soon';
      return `${idx + 1}. Title: ${job.title}
   - Expiry Date (Last Date to Apply): ${formattedExpiry}
   - URL Path: /blog/${job.slug}
   - Summary: ${job.excerpt || 'Latest recruitment details.'}`;
    }).join('\n\n');

    const currentDateStr = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });
    const currentMonthYear = new Date().toLocaleDateString('en-IN', { month: 'long', year: 'numeric' });

    // 5. Build prompt
    const sysPrompt = "You are a professional Hindi Career Counselor, SEO copywriter, and chief editor for Knowora. You generate high-CTR article digests.";
    const userPrompt = `You are tasked with generating a summary digest post of the following ACTIVE job vacancies currently published on our blog.

List of Active Jobs to include:
${activeJobsListStr}

CRITICAL RULES:
1. Title: Create a high-CTR, click-worthy Hindi title in Devanagari script. Include current month/year (e.g. "${currentMonthYear}"). Example: "Top Active Jobs ${currentMonthYear}: इन नौकरियों के फॉर्म भरे जा रहे हैं, जल्द करें आवेदन"
2. Summarization: For each job, write a short, highly professional 2-sentence description in Hinglish/Hindi explaining what the job is and why the candidate should apply now.
3. Strict Linking: You MUST link back to each job's detailed page. Use the exact URL Path provided in the list (e.g. "/blog/job-slug"). Format the link as: <a href="/blog/job-slug" style="color: #2563eb; font-weight: bold; text-decoration: underline;">👉 यहाँ क्लिक करके पूरी जानकारी और आवेदन लिंक देखें</a>
4. Tables: Create a clean summary table of all active jobs at the beginning of the article comparing:
   - विभाग (Department / Post)
   - अंतिम तिथि (Last Date)
   - पूरी जानकारी लिंक (Link to Full Post)
5. Tone: Motivating, career-oriented, direct, and professional. Avoid conversational fluff like "दोस्तों" or "आइए जानते हैं".
6. Return Format: Return a JSON object with this exact structure:
{
  "title": "Your compiled Hindi title",
  "content": "Your complete formatted HTML content starting with intro, followed by the table, followed by individual job summaries with their links, and ending with a disclaimer."
}
Respond ONLY with the JSON. Do not write markdown blocks outside the JSON.`;

    // 6. Generate content
    const rawResponse = await generateContentWithFallback(writerConfig, sysPrompt, userPrompt);
    let parsedData;
    try {
      const match = rawResponse.match(/\{[\s\S]*\}/);
      const cleanJson = match ? match[0] : rawResponse;
      parsedData = JSON.parse(cleanJson);
    } catch (e) {
      console.error("Failed to parse AI digest response:", rawResponse);
      return NextResponse.json({ error: "Failed to parse AI digest response JSON" }, { status: 500 });
    }

    // Determine the latest expiry date among active jobs to set as digest expiry date
    let latestExpiry: Date | null = null;
    for (const job of activeJobs) {
      if (job.expiryDate) {
        const d = new Date(job.expiryDate);
        if (!latestExpiry || d > latestExpiry) {
          latestExpiry = d;
        }
      }
    }

    // 7. Save digest post to database
    const digestSlug = `active-jobs-digest-${currentMonthYear.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${Date.now().toString().slice(-4)}`;
    
    const newPost = await prisma.blogPost.create({
      data: {
        title: parsedData.title,
        slug: digestSlug,
        content: parsedData.content,
        excerpt: `जानिए इस सप्ताह की टॉप सक्रीय सरकारी और प्राइवेट नौकरियों के बारे में। इन सभी के आवेदन फॉर्म फिलहाल चालू हैं। अंतिम तिथि से पहले करें अप्लाई!`,
        status: 'Published',
        publishedAt: new Date(),
        autoGenerated: true,
        expiryDate: latestExpiry,
        seoTitle: parsedData.title,
        seoDescription: `जानिए इस सप्ताह की टॉप सक्रीय सरकारी और प्राइवेट नौकरियों के बारे में। इन सभी के आवेदन फॉर्म फिलहाल चालू हैं।`,
        tags: {
          create: [
            { tag: { connectOrCreate: { where: { name: 'Job Digest' }, create: { name: 'Job Digest', slug: 'job-digest' } } } },
            { tag: { connectOrCreate: { where: { name: 'Education & Career' }, create: { name: 'Education & Career', slug: 'education-career' } } } }
          ]
        }
      }
    });

    // 8. Revalidate paths
    try {
      revalidatePath('/');
      revalidatePath('/blog');
    } catch (e) {}

    // 9. Submit to Google Indexing API
    if (savedKeys.googleIndexingJson) {
      try {
        const { submitToGoogleIndexing } = require('@/lib/google-indexing');
        const postUrl = `https://knowora.in/blog/${newPost.slug}`;
        console.log("[Job Digest] Submitting to Google Indexing API:", postUrl);
        await submitToGoogleIndexing(postUrl, 'URL_UPDATED', savedKeys.googleIndexingJson);
      } catch (e) {
        console.error("[Job Digest] Google Indexing failed:", e);
      }
    }

    // 10. Syndication to Telegram and WhatsApp
    const socialCaption = `📢 *साप्ताहिक नौकरी बुलेटिन (${currentMonthYear})* 📢\n\n${newPost.title}\n\nसभी एक्टिव सरकारी और प्राइवेट जॉब्स के आवेदन फॉर्म फिलहाल चालू हैं।\n\nयहाँ क्लिक करके देखें पूरी लिस्ट और अप्लाई करें: https://knowora.in/blog/${newPost.slug}`;
    const socialImageUrl = `https://www.knowora.in/api/og?title=${encodeURIComponent(newPost.title)}`;

    // Post to Telegram
    if (savedKeys.telegramToken && savedKeys.telegramChatId) {
      try {
        await fetch(`https://api.telegram.org/bot${savedKeys.telegramToken}/sendMessage`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            chat_id: savedKeys.telegramChatId,
            text: socialCaption,
            parse_mode: 'Markdown'
          })
        });
      } catch (e) {
        console.error("[Job Digest] Telegram send failed:", e);
      }
    }

    return NextResponse.json({
      status: 'success',
      message: `Successfully generated active job digest: ${newPost.title}`,
      postId: newPost.id,
      postUrl: `/blog/${newPost.slug}`
    });

  } catch (error: any) {
    console.error('[Active Job Digest Cron Failed]:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
