name: Auto-Blog Scheduled Runner

on:
  schedule:
    # Runs every 10 minutes.
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allows you to manually click "Run workflow" in GitHub Actions tab

jobs:
  ping-production-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Auto-Blog Endpoint
        run: |
          curl -i -X GET "https://www.knowora.in/api/cron/auto-blog?secret=knowora-cron-2026"
